apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-app-dev
  namespace: dev  

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-app-dev

  template:
    metadata:
      labels:
        app: sample-app-dev

    spec:
     containers:
     - name: sample-app-dev
       image: ghcr.io/github1001/devops-lab:dev
       imagePullPolicy: Always

       envFrom:
       - configMapRef:
           name: sample-app-config
       - secretRef:
            name: sample-app-secret

       ports:
       - containerPort: 3000
