apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-app-prod
  namespace: prod  

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-app-prod

  template:
    metadata:
      labels:
        app: sample-app-prod

    spec:
      containers:
      - name: sample-app-prod
        image: ghcr.io/github1001/devops-lab:prod
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
             name: sample-app-config
        - secretRef:
             name: sample-app-secret

        ports:
        - containerPort: 3000
